# Generated by Django 4.2.3 on 2023-07-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
